### ISSUE TITLE
how to download the sfd_face.pth

### ISSUE THREAD

**Issue by songhaozhen** [TaoRuijie/TalkNet_ASD#24]
Thanks for sharing your excellent work! Your code is really friendly and easy to use.

While evaluating the performance of pre-trained model with command: python demoTalkNet.py --videoName 001

The I got the following error message:
demo\001\pyavi\video.avi - scenes detected 1
2021-12-25 21:13:14 Scene detection and save in demo\001\pywork
Traceback (most recent call last):
  File "demoTalkNet.py", line 458, in <module>
    main()
  File "demoTalkNet.py", line 421, in main
    faces = inference_video(args)
  File "demoTalkNet.py", line 97, in inference_video
    DET = S3FD(device='cuda')
  File "D:\python project\TalkNet_ASD-main\model\faceDetector\s3fd\__init__.py", line 27, in __init__
    state_dict = torch.load(PATH, map_location=self.device)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\python project\\TalkNet_ASD-main\\model/faceDetector/s3fd/sfd_face.pth'

how to download the sfd_face.pth

**Comment by TaoRuijie** [comment]
Check the file model/faceDetector/s3fd/__init__.py

Line 9 to Line 14, it will download that file automatically.

If you are using windows. Notice to replace '/' to '\\'

**Comment by songhaozhen** [comment]
it worked.
Thanks
