### ISSUE TITLE
Question Regrading Online Inference

### ISSUE THREAD

**Issue by hsato1** [TaoRuijie/TalkNet_ASD#45]
Hello,

I have been working on investigating ASD online inference and I have been looking at the demo code. 
If we are processing by frames and were in controlled setting, what is the purpose and benefit of using Scene detection?

Thank you very much!
Hiro

**Comment by TaoRuijie** [comment]
Controlled setting means only one scene?

In that case can skip scene detection. Because if the video has multiple scene. The face tracking needs to be continus so scene detection is required

**Comment by hsato1** [comment]
Yes, in a control setting where there won't be drastic changes in background nor number of people who will be talking in the video frame. Since there aren't drastic change I was thinking that scene detection wouldn't be required.

Also, in the paper, you mentioned that 5 video samples that are evenly temporally spaced are extracted but where does that exactly occur in the evaluate_network? Is that a result of the embedding or do you guys actually choose 5 frames before the embedding? 

Thank you!
Hiro

**Comment by TaoRuijie** [comment]
I cannot get your point, where are 5 video samples you mentioned?

**Comment by 2018212596** [comment]
Hello, I have a bug when running the demo file. Can you help me check it?

PS D:\Pycharm\TalkNet-ASD-main> python demoTalkNet.py --videoName 001
d:\programdata\anaconda3\lib\site-packages\gdown\cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "d:\programdata\anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "d:\programdata\anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "d:\programdata\anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1KafnHz7ccT-3IyddBsL5yi2xGtxAKypt (Caused by SSLError(SSLEOFError(8, 'EOF occurr
ed in violation of protocol (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\Scripts\gdown.exe\__main__.py", line 7, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\gdown\cli.py", line 151, in main
    filename = download(
  File "d:\programdata\anaconda3\lib\site-packages\gdown\download.py", line 155, in download
    res = sess.get(url, stream=True, verify=verify)
  File "d:\programdata\anaconda3\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "d:\programdata\anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\programdata\anaconda3\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "d:\programdata\anaconda3\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1KafnHz7ccT-3IyddBsL5yi2xGtxAKypt (Caused by SSLError(SSLEOFError(8, 'EOF occurred i
n violation of protocol (_ssl.c:1125)')))
d:\programdata\anaconda3\lib\site-packages\gdown\cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "d:\programdata\anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "d:\programdata\anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "d:\programdata\anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "d:\programdata\anaconda3\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1AbN9fCf9IexMxEKXLQY2KYBlb-IhSEea (Caused by SSLError(SSLEOFError(8, 'EOF occurr
ed in violation of protocol (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programdata\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\Scripts\gdown.exe\__main__.py", line 7, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\gdown\cli.py", line 151, in main
    filename = download(
  File "d:\programdata\anaconda3\lib\site-packages\gdown\download.py", line 155, in download
    res = sess.get(url, stream=True, verify=verify)
  File "d:\programdata\anaconda3\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "d:\programdata\anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\programdata\anaconda3\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "d:\programdata\anaconda3\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1AbN9fCf9IexMxEKXLQY2KYBlb-IhSEea (Caused by SSLError(SSLEOFError(8, 'EOF occurred i
n violation of protocol (_ssl.c:1125)')))
'ffmpeg' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2023-03-02 02:45:27 Extract the video and save in demo\001\pyavi\video.avi 
'ffmpeg' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2023-03-02 02:45:27 Extract the audio and save in demo\001\pyavi\audio.wav
'ffmpeg' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2023-03-02 02:45:27 Extract the frames and save in demo\001\pyframes
VideoManager is deprecated and will be removed.
Traceback (most recent call last):
  File "demoTalkNet.py", line 458, in <module>
    main()
  File "demoTalkNet.py", line 417, in main
    scene = scene_detect(args)
  File "demoTalkNet.py", line 78, in scene_detect
    videoManager = VideoManager([args.videoFilePath])
  File "D:\ProgramData\Anaconda3\lib\site-packages\scenedetect\video_manager.py", line 294, in __init__
    self._cap_list, self._cap_framerate, self._cap_framesize = open_captures(
  File "D:\ProgramData\Anaconda3\lib\site-packages\scenedetect\video_manager.py", line 147, in open_captures
    raise IOError("Video file(s) not found.")
OSError: Video file(s) not found.

**Comment by TaoRuijie** [comment]
Did you install ffmpeg?

**Comment by hsato1** [comment]
My apologies for such a late response. 

I was referring to the section 5.2.1 but I believe I misunderstood what it was meant.

So it's not 5 evenly spaced samples but rather 5 consecutive samples which represents a short-term video feature with length 0.2. Am I understanding this correctly?

And from the table, the best performance was when we used the length of video that is 2 seconds correct?

Thank you so much again!
Hiro

**Comment by TaoRuijie** [comment]
The best performance is use the entire length, not 2s.

Yes , 5 continuous frames as 0,2s.
