### ISSUE TITLE
No such file or directory: 'demo\\001\\pycrop\\demo\\001\\pycrop\\00000.wav'

### ISSUE THREAD

**Issue by 2018212596** [TaoRuijie/TalkNet_ASD#46]
Hello, I would like to ask what is wrong here. The problem is reported as follows：
PS D:\Pycharm\TalkNet-ASD-main> python demoTalkNet.py --videoName 001
2023-03-06 16:19:46 Extract the video and save in demo\001\pyavi\video.avi 
2023-03-06 16:19:46 Extract the audio and save in demo\001\pyavi\audio.wav 
2023-03-06 16:19:47 Extract the frames and save in demo\001\pyframes 
VideoManager is deprecated and will be removed.
`base_timecode` argument is deprecated and has no effect.
demo\001\pyavi\video.avi - scenes detected 1
2023-03-06 16:19:48 Scene detection and save in demo\001\pywork
2023-03-06 16:20:09 Face detection and save in demo\001\pywork 
2023-03-06 16:20:09 Face track and detected 8 tracks 
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.57it/s] 
2023-03-06 16:20:14 Face Crop and saved in demo\001\pycrop tracks
Model pretrain_TalkSet.model loaded from previous state!
  0%|                                                                                                                                                                                    | 0/8 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File "demoTalkNet.py", line 458, in <module>
    main()
  File "demoTalkNet.py", line 444, in main
    scores = evaluate_network(files, args)
  File "demoTalkNet.py", line 218, in evaluate_network
    _, audio = wavfile.read(os.path.join(args.pycropPath, fileName + '.wav'))
  File "D:\ProgramData\Anaconda3\envs\FYP\lib\site-packages\scipy\io\wavfile.py", line 647, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'demo\\001\\pycrop\\demo\\001\\pycrop\\00000.wav'
PS D:\Pycharm\TalkNet-ASD-main> python demoTalkNet.py --videoName 001
2023-03-06 16:24:03 Extract the video and save in demo\001\pyavi\video.avi 
2023-03-06 16:24:03 Extract the audio and save in demo\001\pyavi\audio.wav 
2023-03-06 16:24:04 Extract the frames and save in demo\001\pyframes 
VideoManager is deprecated and will be removed.
`base_timecode` argument is deprecated and has no effect.
demo\001\pyavi\video.avi - scenes detected 1
2023-03-06 16:24:04 Scene detection and save in demo\001\pywork
2023-03-06 16:24:26 Face detection and save in demo\001\pywork 
2023-03-06 16:24:26 Face track and detected 8 tracks 
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.57it/s] 
2023-03-06 16:24:31 Face Crop and saved in demo\001\pycrop tracks
03-06 16:24:32 Model para number = 15.01
Model pretrain_TalkSet.model loaded from previous state! 
  0%|                                                                                                                                                                                    | 0/8 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demoTalkNet.py", line 458, in <module>
    main()
  File "demoTalkNet.py", line 444, in main
    scores = evaluate_network(files, args)
  File "demoTalkNet.py", line 218, in evaluate_network
    _, audio = wavfile.read(os.path.join(args.pycropPath, fileName + '.wav'))
  File "D:\ProgramData\Anaconda3\envs\FYP\lib\site-packages\scipy\io\wavfile.py", line 647, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'demo\\001\\pycrop\\demo\\001\\pycrop\\00000.wav'

**Comment by TaoRuijie** [comment]
You are using windows, please check the correct path in Windows system.
